M48
; DRILL file {KiCad (6.0.7)} date Sun Dec 25 01:48:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-25T01:48:02-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.6947Y-2.2222
X7.8856Y-2.2222
T2
X7.6829Y-2.103
X7.8974Y-2.103
T0
M30
