M48
; DRILL file {KiCad (6.0.7)} date Thu Jan 12 12:11:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-12T12:11:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.6577Y-1.7976
X4.8486Y-1.7976
T2
X4.6459Y-1.6783
X4.8604Y-1.6783
T0
M30
